version: '3.8'

services:
  finflow-zipkin:
    image: openzipkin/zipkin
    container_name: finflow-zipkin
    ports:
      - "9411:9411"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: finflow-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "check_running" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    name: finflow-network
