# SonarQube Project Configuration
sonar.projectKey=finflow
sonar.projectName=FinFlow Loan Management
sonar.projectVersion=0.0.1-SNAPSHOT

# Path to source directories
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Exclusions
sonar.exclusions=**/test/**, **/target/**, **/.mvn/**

# Encoding
sonar.sourceEncoding=UTF-8

# Jacoco Coverage
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
